void operador_relacional(token_t look);
void leitura_escrita(token_t look,char *nome1, float comp);
void cod_soma(token_t look);
void cod_multiplicacao(void);
void cod_divisao(void);
void cod_not(void);
void cod_empilha(token_t look);
void cod_empilha2(int n);
void cod_mod_div(token_t look);
void cod_and_or(token_t look);
void cod_inicfunc(char *nome);
void cod_rotulofunc(char *nome);
void cod_ret(void);
void cod_regati(void);
void emitLabel(int label);
void emitGofalse(int label);
void emitGotrue(int label);
void emitGoto(int label);
int verifica_tipo(int t1, int t2);
void empilha_acc(void);
void l_val(char *nome,int off,int l);
void call_func(char *nome);
void comp_case(int look);
void termina(void);
void termina_for(char *nome);
void cod_bss(void);
void cod_rodata(void);
void rotulo_ct(char *nome);
void define_ct(int i,char *nome,int num,float num2);
void inicio(char *str);
