void appendix(void);
void E(void);
void variavel(void);
void constante(void);
void F(void);
void T(void);
void block(void);
void comando(void);
void inseretabela(int off, int tipo);	
void tiposimples(void);
void parlist(void);
void argdecl(void);
void header(void);
void methods(void);
void declist(void);
void tipodcl(void);
void trypascal(void);
void putoffset(int t,int p);

extern FILE *arq;
extern int level;
extern int reg_ati;
extern char arg[16][256];
extern int param;
extern int pos;
